// PrizeDrawsDaily aggregator — production orchestrator (multi-operator, rotating).
//   DRY_RUN=true (default) prints; DRY_RUN=false inserts (needs SUPABASE_SERVICE_ROLE_KEY).
// Operators come from operators.json (generated by probe-all.mjs). To stay within the free LLM
// tier (~150 calls/day), operators are split into BATCHES and ONE batch runs per day (rotates by
// date), with a hard MAX_DRAWS cap as a backstop.
import { chromium } from "playwright";
import { renderOperator, wooOperator, shopifyOperator, dedupe, evaluate, makeContext, CATEGORIES, WINDOW_DAYS } from "./extractor.mjs";

const SUPABASE_URL = process.env.SUPABASE_URL || "https://kkuuwksgyypicnblwubs.supabase.co";
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || "";
const ANON_KEY = process.env.SUPABASE_PUBLISHABLE_KEY || "sb_publishable_h-iA9nWMpXeZHX8uA1Yeyw_3xh_XPKs";
const DRY_RUN = process.env.DRY_RUN !== "false";
const PUBLISH_STATUS = process.env.PUBLISH_STATUS || "draft";
const PER_OP = Number(process.env.PER_OP || 5);
const BATCHES = Number(process.env.BATCHES || 2);       // split operators across N daily runs
const MAX_DRAWS = Number(process.env.MAX_DRAWS || 130); // backstop cap on LLM calls per run
const ONLY = process.env.ONLY ? new Set(process.env.ONLY.split(",")) : null; // slug filter (testing)
const READ_KEY = SERVICE_KEY || ANON_KEY;

const now = new Date();
const round2 = (n) => Math.round(n * 100) / 100;
const slugify = (s) => (s || "draw").toLowerCase().replace(/&/g, " and ").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60) || "draw";

async function sbGet(path) {
  const r = await fetch(`${SUPABASE_URL}/rest/v1/${path}`, { headers: { apikey: READ_KEY, Authorization: `Bearer ${READ_KEY}` } });
  if (!r.ok) throw new Error(`GET ${path} → ${r.status} ${await r.text()}`);
  return r.json();
}
async function sbInsert(rows) {
  const r = await fetch(`${SUPABASE_URL}/rest/v1/draws`, {
    method: "POST",
    headers: { apikey: SERVICE_KEY, Authorization: `Bearer ${SERVICE_KEY}`, "Content-Type": "application/json", Prefer: "return=representation" },
    body: JSON.stringify(rows),
  });
  if (!r.ok) throw new Error(`INSERT → ${r.status} ${await r.text()}`);
  return r.json();
}

// Supervisor: flags suspicious values; flagged draws are always held as 'draft' for review.
function supervisor(d) {
  const flags = [];
  const pool = d.ticket_price * d.total_entries;
  if (d.ticket_price > 50) flags.push(`ticket £${d.ticket_price} >£50?`);
  if (d.total_entries > 5_000_000) flags.push(`${d.total_entries} entries >5M?`);
  if (pool > 50_000_000) flags.push(`pool £${Math.round(pool)} >£50M?`);
  if (["car-draws", "house-draws"].includes(d.category) && pool < 5000) flags.push(`${d.category} pool only £${Math.round(pool)}`);
  if (!/^https?:\/\/.+/.test(d.image_url || "")) flags.push("missing/bad image");
  if (!CATEGORIES.includes(d.category)) flags.push(`bad category ${d.category}`);
  if (!d.description || d.description.length < 20) flags.push("thin description");
  return flags;
}

// ---- pick operators for this run (rotate by day; ONLY overrides for testing) ----
let operators = await Bun.file("operators.json").json();
if (ONLY) operators = operators.filter((o) => ONLY.has(o.slug));
const dayOfYear = Math.floor((now - new Date(now.getFullYear(), 0, 0)) / 864e5);
const batch = dayOfYear % BATCHES;
if (!ONLY && BATCHES > 1) operators = operators.filter((_, i) => i % BATCHES === batch);

console.log(`${DRY_RUN ? "DRY RUN" : "LIVE"} — ${now.toISOString()} | batch ${batch + 1}/${BATCHES} | ${operators.length} operators | PER_OP ${PER_OP} | cap ${MAX_DRAWS} | status '${PUBLISH_STATUS}'\n`);
if (!DRY_RUN && !SERVICE_KEY) { console.error("DRY_RUN=false needs SUPABASE_SERVICE_ROLE_KEY"); process.exit(1); }

const cats = await sbGet("categories?select=id,slug");
const catMap = Object.fromEntries(cats.map((c) => [c.slug, c.id]));
const dbOps = await sbGet("operators?select=id,slug");
const opMap = Object.fromEntries(dbOps.map((o) => [o.slug, o.id]));
const existing = await sbGet("draws?select=entry_url,slug");
const seenUrls = new Set(existing.map((d) => d.entry_url).filter(Boolean));
const takenSlugs = new Set(existing.map((d) => d.slug));
console.log(`loaded ${cats.length} cats, ${dbOps.length} operators, ${existing.length} existing draws\n`);

const browser = await chromium.launch({ headless: true, args: ["--disable-blink-features=AutomationControlled"] });
const ctx = await makeContext(browser);

const toInsert = [];
let calls = 0, skipped = 0;
for (const op of operators) {
  if (calls >= MAX_DRAWS) { console.log(`\n⏹ hit MAX_DRAWS cap (${MAX_DRAWS}) — remaining operators run next time`); break; }
  if (!opMap[op.slug]) { console.log(`· ${op.name}: not in DB, skip`); continue; }
  console.log(`\n── ${op.name} (${op.method}) ──`);
  let draws = [];
  try {
    if (op.method === "woo") draws = await wooOperator(op, PER_OP);
    else if (op.method === "shopify") draws = await shopifyOperator(op, PER_OP);
    else draws = await renderOperator(ctx, op, PER_OP);
  } catch (e) { console.log(`  FAILED: ${(e.message || "").slice(0, 80)}`); continue; }
  calls += draws.length;
  draws = dedupe(draws);
  for (const d of draws) {
    const { pass } = evaluate(d, now);
    if (!pass) { skipped++; continue; }
    if (seenUrls.has(d.entry_url)) { skipped++; continue; }
    seenUrls.add(d.entry_url);
    const slug = (() => { let s = slugify(d.title), i = 2; while (takenSlugs.has(s)) s = `${slugify(d.title)}-${i++}`; takenSlugs.add(s); return s; })();
    const flags = supervisor(d);
    toInsert.push({
      row: {
        slug, operator_id: opMap[op.slug], category_id: catMap[d.category] || null,
        title: d.title, grand_prize: d.grand_prize, prize_description: d.description,
        image_url: d.image_url, ticket_price: d.ticket_price, total_entries: d.total_entries,
        total_prize_value: round2(d.ticket_price * d.total_entries), prize_value: null,
        draw_date: d.draw_date, entry_url: d.entry_url, affiliate_url: null,
        status: flags.length ? "draft" : PUBLISH_STATUS, featured: false,
      },
      flags,
    });
    console.log(`  ✅ ${d.title.slice(0, 44)} | ${d.category} | £${d.ticket_price}×${d.total_entries}${flags.length ? "  ⚠️→draft: " + flags.join("; ") : ""}`);
  }
}
await browser.close();

console.log(`\n\n==== ${toInsert.length} new draws (${calls} pages read, ${skipped} skipped) ====`);
if (DRY_RUN) {
  console.log("(dry run — nothing written)");
} else if (toInsert.length) {
  let inserted = 0;
  for (let i = 0; i < toInsert.length; i += 50) {
    const res = await sbInsert(toInsert.slice(i, i + 50).map((x) => x.row));
    inserted += res.length;
  }
  const live = toInsert.filter((x) => x.row.status === "active").length;
  console.log(`✅ inserted ${inserted} (${live} live, ${inserted - live} held as draft for review)`);
} else {
  console.log("nothing new to insert");
}
